### ISSUE TITLE
SkyMap textures are only filled half with the sky texture

### ISSUE THREAD

**Issue by DomenicDev** [DomenicDev/Crucified#23]
The textures, west, east, front, back are only filled half with the sky texture, the rest is black. So if the player stands on a little higher position and looks down, he is able to see the black part of the sky map. 

A possible solution would be to take those half, flip it and place it on the black area of the texture.

**Comment by 8Keep** [comment]
The goal eventually (for me) is to have a dynamic sky with shaders and atmospheric scattering, so this is low priority.

**Comment by DomenicDev** [comment]
That of course would be more than awesome ;-)

**Comment by DomenicDev** [comment]
We found another sky texture which fit our needs reasonable.
